
[general]

	[general.general]
		chat_prefix = "&f[&6Hysentials&f]"

[guild]

	[guild.guild]
		guild_welcome_message = false

[chat]

	[chat.player_count_chat]
		player_count_chat = false
		leave_player_count_chat = true

	[chat.statuses]
		remove_lobby_statuses = false
		"remove_friend/guild_statuses" = false

	[chat.announcements]
		game_announcements = false
		hype_limit_reminder = false
		hide_mystery_box_messages = false
		soul_well = false

	[chat.misc]
		bedwars_advertisements = false
		short_channel_names = false
		"mvp++_emoji_remover" = false
		white_chat = false
		white_private_messages = false

[qol]

	[qol.chat_swapper]
		chat_swapper_enabled = true
		chat_swapper_channel = "all"
		hide_swap_message = true

	[qol.qol]
		autocomplete_play_commands = true

